### ISSUE TITLE
Traditional songs

### ISSUE THREAD

**Issue by davidabian** [emijrp/wikiradio#2]
Where could we add traditional songs like these?
- [La doncella guerrera](https://commons.wikimedia.org/wiki/File:Fundaci%C3%B3n_Joaqu%C3%ADn_D%C3%ADaz_-_ATO_00001_23_-_La_doncella_guerrera.ogg)
- [La hija de Juan Simón](https://commons.wikimedia.org/wiki/File:Fundaci%C3%B3n_Joaqu%C3%ADn_D%C3%ADaz_-_ATO_00081_13_-_La_hija_de_Juan_Sim%C3%B3n.ogg)
- [Dime, niño, de quién eres](https://commons.wikimedia.org/wiki/File:Fundaci%C3%B3n_Joaqu%C3%ADn_D%C3%ADaz_-_ATO_00486_01_-_Villancico.ogg)

**Comment by wilfredor** [comment]
La lista de archivos, según mi opinión, debe ser tomada desde una categoría
con mediawiki api y no de una lista estatica

2015-12-10 17:38 GMT-02:00 David Abián notifications@github.com:

**Comment by emijrp** [comment]
@davidabian We could create a new channel, Folk music? https://en.wikipedia.org/wiki/Folk_music

**Comment by emijrp** [comment]
@wilfredor Puedes crear un prototipo que funcione de esa forma?

**Comment by wilfredor** [comment]
@davidabian Comments are in https://meta.wikimedia.org/wiki/Talk:Wikiradio_(tool)

**Comment by wilfredor** [comment]
Yes, I could do that

2016-02-03 11:13 GMT-02:00 Emilio J. Rodríguez-Posada <
notifications@github.com>:
