### ISSUE TITLE
Support mp3

### ISSUE THREAD

**Issue by bodhisattwawiki** [emijrp/wikiradio#5]
mp3 files are now supported in Commons. It would be great if Wikiradio also supports mp3 files.

**Comment by Ainali** [comment]
Ah, I was just here to report a bug that [my newly added playlist](https://tools.wmflabs.org/wikiradio/index.php?channel=Wikipediapodden-English) didn't work and now I know why.

**Comment by wilfredor** [comment]
Problem was solved in a recent merge request
